// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    HeaderMenu: typeof import('./components/HeaderMenu.vue')['default']
    KlayButton: typeof import('./common/KlayButton.vue')['default']
    KlayCollapse: typeof import('./common/KlayCollapse.vue')['default']
    KlayIcon: typeof import('./common/KlayIcon.vue')['default']
    KlayLoader: typeof import('./common/KlayLoader.vue')['default']
    KlayModal: typeof import('./common/KlayModal.vue')['default']
    KlaySlider: typeof import('./common/KlaySlider.vue')['default']
    KlaySlippage: typeof import('./common/KlaySlippage.vue')['default']
    KlayTextField: typeof import('./common/KlayTextField.vue')['default']
    KlayWrap: typeof import('./common/KlayWrap.vue')['default']
    LiquidityAdd: typeof import('./components/liquidity/add/LiquidityAdd.vue')['default']
    LiquidityAddExchangeRate: typeof import('./components/liquidity/add/LiquidityAddExchangeRate.vue')['default']
    LiquidityAddModal: typeof import('./components/liquidity/add/LiquidityAddModal.vue')['default']
    LiquidityRemove: typeof import('./components/liquidity/remove/LiquidityRemove.vue')['default']
    LiquidityRemoveAmount: typeof import('./components/liquidity/remove/amount/LiquidityRemoveAmount.vue')['default']
    LiquidityRemoveDetailed: typeof import('./components/liquidity/remove/detailed/LiquidityRemoveDetailed.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swap: typeof import('./components/swap/Swap.vue')['default']
    SwapDetails: typeof import('./components/swap/SwapDetails.vue')['default']
    SwapExchangeRate: typeof import('./components/swap/SwapExchangeRate.vue')['default']
    TagName: typeof import('./components/tag-name/TagName.vue')['default']
    TokenInput: typeof import('./components/token-input/TokenInput.vue')['default']
    TokenSelect: typeof import('./components/token-select/TokenSelect.vue')['default']
    TokenSelectModal: typeof import('./components/token-select/TokenSelectModal.vue')['default']
    Tutorial: typeof import('./components/Tutorial.vue')['default']
  }
}

export {}
